# Generated by Django 5.1.7 on 2025-04-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_desc_category_description_alter_category_slug'),
        ('comments', '0001_initial'),
        ('news', '0002_alter_new_slug'),
        ('tags', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
